---
# tasks file for mattermost
- name: downloading the latest package
  ansible.builtin.get_url:
    url: https://releases.mattermost.com/7.5.2/mattermost-7.5.2-linux-amd64.tar.gz
    dest: mattermost-7.5.2-linux-amd64.tar.gz

- name: Adding mattermost user
  ansible.builtin.add_user:
    name: mattermost

- name: Creating required dirctories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: mattermost
    group: mattermost
    mode: g+w
  loop: "{{ directory }}"

- name: Extracting tar.gz
  ansible.builtin.unarchive:
    src: mattermost-7.5.2-linux-amd64.tar.gz
    dest: /opt/mattermost

- name: Creating configuration files and serivce file
  ansible.builtin.template:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    mode: 0644

- name: Starting and enabling Service
  ansible.builtin.systemd:
    name: mattermost.service
    state: started
    enabled: yes