---
# tasks file for add_users
- name: Adding users to mattermost 
  ansible.builtin.uri:
    url: "{{ baseurl }}/api/v4/users"
    method: POST
    headers:
      Authorization: Bearer {{ token }}
      Content-Type: application/json
    body_format: json
    body:
      email: "{{item.email}}"
      username: "{{ item.name }}"
      first_name: "{{ item.firstname }}"
      last_name: "{{ item.surname }}"
      nickname: "{{ item.firstname }} {{ item.surname }}"
      password: Welcome123!
    return_content: yes
    status_code: 201,400
  delegate_to: localhost
  loop: "{{ users }}"

- name: Getting ID's of all the users
  ansible.builtin.uri:
    url: "{{ baseurl }}/api/v4/users"
    method: GET
    headers:
      Authorization: Bearer {{ token }}
      Content-Type: application/json
    body_format: json
    return_content: yes
    status_code: 200
  delegate_to: localhost
  register: mm_users

- name: Adding users to Mattermost Channel
  ansible.builtin.uri:
    url: "{{ baseurl }}/api/v4/teams/{{ team_id }}/members"
    method: POST
    headers:
      Authorization: Bearer {{ token }}
      Content-Type: application/json
    body_format: json
    body:
      team_id: "{{ team_id }}"
      user_id: "{{ item.id }}"
      roles: team_user
    return_content: yes
    status_code: 201,400
  delegate_to: localhost
  loop: "{{ mm_users.json }}"

- name: Verify users email
  ansible.builtin.uri:
    url: "{{ baseurl }}/api/v4/users/{{ item.id }}/email/verify/member"
    method: POST
    headers:
      Authorization: Bearer {{ token }}
      Content-Type: application/json
    body_format: json
    return_content: yes
    status_code: 200
  delegate_to: localhost
  loop: "{{ mm_users.json }}"

